# \u683C\u5F0F\uFF1Aalias.jdbcUrl / alias.username / alias.password / alias.driverClassName

# MySQL encrypt
default.jdbcUrl=jdbc:mysql://127.0.0.1:3306/std_bg
default.username=cm9vdA==
default.password=cm9vdA==
default.driverClassName=com.mysql.cj.jdbc.Driver
default.encrypt=com.genesis.sql.DecUtil

# MySQL nonencrypt
#default.jdbcUrl=jdbc:mysql://127.0.0.1:3306/std_bg
#default.username=root
#default.password=root
#default.driverClassName=com.mysql.cj.jdbc.Driver



# MSSQL \u7BC4\u4F8B
#mssql1.jdbcUrl=jdbc:sqlserver://127.0.0.1:1433;databaseName=reportdb1
#mssql1.username=sa
#mssql1.password=abcd
#mssql1.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver



# Oracle \u7BC4\u4F8B
#oracle1.jdbcUrl=jdbc:oracle:thin:@127.0.0.1:1521:orcl1
#oracle1.username=system
#oracle1.password=oracle
#oracle1.driverClassName=oracle.jdbc.OracleDriver


