# Sample ResourceBundle properties file
# For application's changeable attributes.

# CSP setting (cspString)
csp.string.default=default-src 'self' https://www.google.com/ https://cdn.jsdelivr.net https://fonts.googleapis.com https://fonts.gstatic.com https://www.youtube.com https://googleads.g.doubleclick.net https://www.google-analytics.com/ https://cdnjs.cloudflare.com https://maps.googleapis.com ;
csp.string.script=script-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com https://code.jquery.com https://www.google-analytics.com/ https://www.googletagmanager.com https://unpkg.com https://maps.googleapis.com  ;
csp.string.style=style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://fonts.googleapis.com https://cdnjs.cloudflare.com https://unpkg.com ;
csp.string.img=img-src 'self' ;
csp.string.frame=frame-ancestors 'self';
csp.string.frameSrc=frame-src 'self' https://www.google.com/maps/  https://www.youtube.com/;
require.trusted.types.for= ;

# The relative folder of uploaded files.
folder.upload=/uploads

# The relative folder of uploaded attach files.
#folder.upload.attach=/uploads/attach

# The SMTP mail server name.
mail.smtp.host=

# The service provider's email address.
mail.service.email=
# The service provider's name.
mail.service.name=

# The epaper sender's email address.
mail.epaper.email=

# The epaper sender's name.

mail.epaper.name=

# The title of this site.

title.web=\u918d\u9190\u5927\u5e2b

# The title of management of this site.
title.mis=\u918d\u9190\u5927\u5e2b

# The service account for Genesis stuff.
genesis.username=

# The service password for Genesis stuff.
genesis.password=

# The default user name for Client MIS.
default.username=

# The default password for Client MIS.
default.password=

#\u9996\u9801\u9810\u8A2D\u8A9E\u7CFB
default.locale=tw;
